version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=jyami
      - MYSQL_PASSWORD=jyami-password
      - MYSQL_DATABASE=jyami
      - TZ=Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/config:/etc/mysql/conf.d
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "33306:3306"
