home:
  name: jyami


spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jyami
    username: jyami
    password: test
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        show_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
      generate-ddl: true
      properties:
      temp:
        use_jdbc_metadata_defaults: false
